name: robot_ci

on: 
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-20.04
    container:
      image: docker://wpilib/roborio-cross-ubuntu:2022-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew build